add field validation component
10up/block-components pull request #238
Opened 2023-07-07 07:52 UTC by darrenjacoby

### Description

This PR creates a new `<FieldValidation>` component that can be used for required fields or fields that require custom tests for validation.

- Fields can be marked as required.
- Fields can have custom validation tests and messaging.
- Editor "update" button is disabled if any field validation is failing on the post or page.

Screenshots below of failing field validations.

<img width="206" alt="image" src="https://github.com/10up/block-components/assets/15921694/495d2a10-eb21-4b69-9a26-beb763c69f95">
<img width="314" alt="image" src="https://github.com/10up/block-components/assets/15921694/85f194be-1749-46e9-830c-24af3d46886e">

### Testing

Import `<FieldValidation>` and test with the following block editor code.

```js
import { FieldValidation } from '@10up/block-components';

function BlockEdit(props) {
    const { attributes, setAttributes } = props;
    const { title } = attributes;

    return (
        <>
            <FieldValidation
                value={title}
                required={__('Title is a required field', '10up-block-library')}
                validate={[
                    [ (value) => /^[a-zA-Z\s]+$/.test(value), __('Title requires alphabetical characters', '10up') ],
                    [ (value) => /^.{10,}$/.test(value), __('Title requires 10 characters or more', '10up') ],
                ]}
            >
                    <RichText
                        tagName="p"
                        value={title}
                        onChange={(value) => setAttributes({ title: value })}
                    />
            </FieldValidation>
        </>
    )
}
```

### Changelog
> Added - <FieldValidation>

### Credits
n/a

### Checklist
- [x ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ x] All new and existing tests pass.

2023-07-28 09:12 UTC, fabiankaegy requested changes
This is really cool and works like a charm! Thank you for your contribution! 

The only thing I would like to workshop a little bit more is how we style the inline errors. Using floatingUI is great and solves most of our issues already. However I think we should maybe think about making the entire background a solid color so we can ensure legibility. 

@Sidsector9 implemented a similar thing in https://github.com/10up/block-components/pull/235 which we may be able to use as an inspiration. 

Maybe @xavortm also has an idea of what this could look like :)

2023-07-28 09:12 UTC, fabiankaegy commented on components/field-validation/index.js
> +		const res = typeof required === 'string' ? required : __('Required', '10up-block-library');
```suggestion
		const res = typeof required === 'string' ? required : __('Required', '10up-block-components');
```

2023-07-28 09:51 UTC, darrenjacoby commented on components/field-validation/index.js
> +		const res = typeof required === 'string' ? required : __('Required', '10up-block-library');
Oops, corrected.

2023-07-28 09:58 UTC, darrenjacoby commented
Hey @fabiankaegy ,

Thanks for taking a look! There's probably a good case to be made for leaving styling options to developers on each project to account for things like dark-mode/brand colors, etc. But definitely open to design suggestions for defaults.

In the interim, pushed an update which implements an error class on the field itself.

- `.tenup--block-components__validation-error__field` to style the field. For example, adding `background-color: red;` will made the field background red.

<img width="729" alt="image" src="https://github.com/10up/block-components/assets/15921694/ad08074d-d641-40ab-9368-7c3d4f1c2af2">

There are two other available custom classes;

- `.tenup--block-components__validation-error__response` to style the response container.
- `.tenup--block-components__validation-error__response-rule` to style each response individual rule (as there can be multiple rule failures).

2023-07-28 10:38 UTC, fabiankaegy commented
I love the addition of the classes. 

However, I kind of disagree that it should be up to the developer to determine how the invalid state should look. The validation issue is not part of the content and counts as part of the editor frame. Having a standardized way to showcase invalid content which then can be overwritten, but in most cases doesn't need to be overwritten, is what I would prefer here. 

The goal of the block components is to remove as much complexity from the developers on individual projects. And having to re-invent how to style the invalid state of a component in the editor doesn't add a lot of value to a client in my perspective. And it creates the risk that when not styled correctly we create very unclear confusing experiences where a user doesn't understand why they are not able to save the post. 

That isn't to say that I don't want anyone to be able to overwrite the default styling. But I think there should be decent opinionated default styling that makes it look as though it were a core API and part of the native editor experience. So using the editors font, color scheme etc.

2023-07-28 10:42 UTC, darrenjacoby commented
@fabiankaegy those are good points which all make sense to me! Let’s see how we can implement a nice default state 🙂

2023-07-28 15:33 UTC, darrenjacoby commented
I've implemented some basic styling which matches some WordPress defaults. I'll await feedback from [xavortm](https://github.com/xavortm).

Responses;
- Default WordPress font stack
- Font size 13px
- Font weight 500
- WordPress color `var(--wp--preset--color--vivid-red)`

Field;
- Background color of `var(--wp--preset--color--vivid-red)` at 75% opacity.

Example on dark background; 
<img width="523" alt="image" src="https://github.com/10up/block-components/assets/15921694/e27519b3-0435-4a02-864f-4b5694140b08">

Example on light background;
<img width="510" alt="image" src="https://github.com/10up/block-components/assets/15921694/6905c260-e523-4985-a97b-4f881d1294bb">

2023-08-03 07:33 UTC, xavortm commented
Hi! Joining with some design proposals about the validation UI/UX:

Please see here: https://www.figma.com/file/YtfzsSMXZJb2N2pfnuuAI3/Blocks-validation?type=design&node-id=0%3A1&mode=design&t=HeaSOLhTcoyL21Rc-1

I have listed the steps and states, including singular and combinations blocks (like core/blocks). 

For visual guide/direction, please see the blue section marked as "Ready for dev" on the right. Here is also a screenshot from it:

<img width="605" alt="Screenshot 2023-08-03 at 10 30 20@2x" src="https://github.com/10up/block-components/assets/2004664/67de2dc4-1963-4df4-8f3d-c0e9d1fae278">

It uses a component from Gutenberg but also adds a slight shadow to work better on white backgrounds. The Figma docs point to https://developer.wordpress.org/block-editor/how-to-guides/notices/ for the component reference.

2024-04-06 09:01 UTC, closed without merging